title: "Sean"
author: "Sean McGowan"
description: "I prostrate to those who have abandoned all views"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header


# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "Projects.md", title: 'Projects'}
  - {file: "(ACTIVE) Sean_McGowan_Resume-4.pdf", title: 'CV'}
  - {file: "Sean_blog.md", title: 'Blog'}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:seankellymcgowan@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/bigtimecodersean"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/seanqualia"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
